### ISSUE TITLE
自动收集原生自定义组件的 props 和 events

### ISSUE THREAD

**Issue by b2nil** [wechat-miniprogram/kbone#38]
现在使用自定义组件必须通过 webpack 配置来完成：
```
wxCustomComponent: {
	root: path.join(__dirname, '../src/custom-components'),
	usingComponents: {
		'comp-a': {
			path: 'comp-a',
			props: ['prefix', 'suffix'],
			events: ['someevent'],
		},
		'comp-b': {
			path: 'comp-b/index',
			props: ['prefix'],
		},
		'comp-c': 'comp-c',
	},
},
```
这样引用第三方小程序 UI 库太费劲了。

能不能支持自动收集组件的 `props` 和 `events`, 只声明组件的的名称和路径？
或者更友好地直接作为 `Vue` 或 `React` 组件引用， 而无需申明 `useComponents`：
```
import CustomizedComp from 'thirdparty/weapp-ui/comp'; 
```

**Comment by JuneAndGreen** [comment]
曾经想过给模板预处理时进行收集，但是问题在于这种只能做静态处理，而且得针对不同的模板得实现不同的预处理器（比如有些 Web 框架监听自定义事件只能走 addEventListener，这种无法收集）。另外 kbone 本身的设计是针对 Web 端代码在小程序执行的适配层，但是要将小程序组件完美转成 Vue/React 组件目前是做不到的，因为特性不对等就会导致功能上的残缺，所以这里就改成用声明式。

另外这个声明其实不是这个组件有什么就要加什么，而是用到了什么再加什么，比如这个组件有五个事件，业务只用到了其中一个，就只声明这一个就行。这个功能是针对可以复用一些已有的小程序自定义组件，如果可以的话比较推荐使用 Web 端的组件，如果大量使用小程序自定义组件会带来一定程度的性能损耗。

**Comment by b2nil** [comment]
关注｀kbone｀的原因就因为这一条：

> kbone 本身的设计是针对 Web 端代码在小程序执行的适配层

特别希望能够在小程序上使用如｀vuetify｀和`Material-UI`等框架的一些组件。
试了一下`preact` + `Material-UI`，编译都正常，但在小程序上没有渲染出来。
需要在`webpack`配置里添加什么特别的操作吗？

**Comment by b2nil** [comment]
在 React + Kbone 模板中引入 Material-UI 的组件后，报了以下错误。这还有救吗？
```
Cannot read property 'appendChild' of null;at "pages/index/index" page lifeCycleMethod onLoad function
TypeError: Cannot read property 'appendChild' of null
    at insertStyle (http://127.0.0.1:64232/appservice/common/vendors~index.js:2206:12)
    at DomRenderer.attach (http://127.0.0.1:64232/appservice/common/vendors~index.js:2291:5)
    at StyleSheet.attach (http://127.0.0.1:64232/appservice/common/vendors~index.js:1563:38)
    at attach (http://127.0.0.1:64232/appservice/common/vendors~index.js:4491:19)
    at http://127.0.0.1:64232/appservice/common/vendors~index.js:4625:7
    at useSynchronousEffect (http://127.0.0.1:64232/appservice/common/vendors~index.js:4578:14)
    at http://127.0.0.1:64232/appservice/common/vendors~index.js:4617:5
    at WithStyles (http://127.0.0.1:64232/appservice/common/vendors~index.js:4709:21)
    at Ih (http://127.0.0.1:64232/appservice/common/vendors~index~log.js:339:98)
    at ni (http://127.0.0.1:64232/appservice/common/vendors~index~log.js:357:192)
```
查看 `vendors~index.js` 发现：
```
/**
 * Gets the `head` element upon the first call and caches it.
 * We assume it can't be null.
 */
var getHead = memoize(function () {
  // 这里返回的是 null， 从而导致 insertStyle 的时候 getHead().appendChild(style) 报错
  return document.querySelector('head');  
});
```

另外， 开发者工具显示以下 Warning：
```
VM151:1 window.getComputedStyle is not supported, please use window.$$getComputedStyle instead of it
```
将`window.getComputedStyle`更改为`window.$$getComputedStyle`后，报错：
```
window.js:215 Uncaught (in promise) TypeError: _this3.$$createSelectorQuery is not a function
    at window.js:215
    at new Promise (<anonymous>)
    at Window.$$getComputedStyle (window.js:211)
    at Object.<anonymous> (vendors~index.js:3948)
    at __webpack_require__ (index.js:81)
    at Module.21 (index.js:188)
    at __webpack_require__ (index.js:81)
    at checkDeferredModules (index.js:47)
    at index.js:154
    at module.exports (index.js:157)
```

**Comment by b2nil** [comment]
鉴于 kbone 的设计宗旨比较明确，先把这个关闭了。 

后面的问题另外开了 Issue #40 咨询。
