### ISSUE TITLE
在 React + Kbone 模板中引入 Material-UI 组件小程序端报错

### ISSUE THREAD

**Issue by b2nil** [wechat-miniprogram/kbone#40]
在 React + Kbone 模板中引入 Material-UI 的组件后，小程序端报了以下错误。这还有救吗？
```
Cannot read property 'appendChild' of null;at "pages/index/index" page lifeCycleMethod onLoad function
TypeError: Cannot read property 'appendChild' of null
    at insertStyle (http://127.0.0.1:64232/appservice/common/vendors~index.js:2206:12)
    at DomRenderer.attach (http://127.0.0.1:64232/appservice/common/vendors~index.js:2291:5)
    at StyleSheet.attach (http://127.0.0.1:64232/appservice/common/vendors~index.js:1563:38)
    at attach (http://127.0.0.1:64232/appservice/common/vendors~index.js:4491:19)
    at http://127.0.0.1:64232/appservice/common/vendors~index.js:4625:7
    at useSynchronousEffect (http://127.0.0.1:64232/appservice/common/vendors~index.js:4578:14)
    at http://127.0.0.1:64232/appservice/common/vendors~index.js:4617:5
    at WithStyles (http://127.0.0.1:64232/appservice/common/vendors~index.js:4709:21)
    at Ih (http://127.0.0.1:64232/appservice/common/vendors~index~log.js:339:98)
    at ni (http://127.0.0.1:64232/appservice/common/vendors~index~log.js:357:192)
```
查看 `vendors~index.js` 发现：
```
/**
 * Gets the `head` element upon the first call and caches it.
 * We assume it can't be null.
 */
var getHead = memoize(function () {
  // 这里返回的是 null， 从而导致 insertStyle 的时候 getHead().appendChild(style) 报错
  return document.querySelector('head');  
});
```

另外， 开发者工具显示以下 Warning：
```
VM151:1 window.getComputedStyle is not supported, please use window.$$getComputedStyle instead of it
```
将`window.getComputedStyle`更改为`window.$$getComputedStyle`后，报错：
```
window.js:215 Uncaught (in promise) TypeError: _this3.$$createSelectorQuery is not a function
    at window.js:215
    at new Promise (<anonymous>)
    at Window.$$getComputedStyle (window.js:211)
    at Object.<anonymous> (vendors~index.js:3948)
    at __webpack_require__ (index.js:81)
    at Module.21 (index.js:188)
    at __webpack_require__ (index.js:81)
    at checkDeferredModules (index.js:47)
    at index.js:154
    at module.exports (index.js:157)
```

**Comment by raphealguo** [comment]
小程序的逻辑层和渲染层分离，所以获取样式这种同步接口 getComputedStyle， kbone 没法模拟，只能靠第三方UI库做一些简单的适配。

**Comment by b2nil** [comment]
谢谢解答。
