### ISSUE TITLE
eval is not a function

### ISSUE THREAD

**Issue by Double-Lv** [wechat-miniprogram/kbone#68]
按照**kbone 项目搭建流程**操作了一遍，开发工具构建npm后预览，报如下错，不知道是什么原因，麻烦帮忙看看~
PS.基础库版本和开发工具版本都检查无误

VM226:1 thirdScriptError
eval is not a function;at "pages/home/index" page lifeCycleMethod onLoad function
TypeError: eval is not a function
    at Object../src/mp/entry-mp.js (http://127.0.0.1:29103/appservice/common/home.js:190:1)
    at __webpack_require__ (http://127.0.0.1:29103/appservice/common/home.js:80:30)
    at checkDeferredModules (http://127.0.0.1:29103/appservice/common/home.js:47:23)
    at http://127.0.0.1:29103/appservice/common/home.js:153:18
    at module.exports (http://127.0.0.1:29103/appservice/common/home.js:156:10)
    at init (http://127.0.0.1:29103/appservice/pages/home/index.js:10:34)
    at ge.onLoad (http://127.0.0.1:29103/appservice/pages/home/index.js:134:5)
    at ge.<anonymous> (http://127.0.0.1:29103/appservice/__dev__/WAService.js:1:1454082)
    at ge.p.__callPageLifeTime__ (http://127.0.0.1:29103/appservice/__dev__/WAService.js:1:1453827)
    at Tt (http://127.0.0.1:29103/appservice/__dev__/WAService.js:1:1469217)

**Comment by JuneAndGreen** [comment]
小程序本身不支持 eval 和 new Function，你应该是有用到动态引入组件/js 之类的吧，这块在小程序中你就直接改成静态引入就好了
