### ISSUE TITLE
vue-cli-plugin-kbone插件运行报Callback was already called

### ISSUE THREAD

**Issue by huoxiangdong** [wechat-miniprogram/kbone#80]
请教下，这是什么原因
```bash
 yarn mp
yarn run v1.19.2
$ cross-env MP_ENV=miniprogram vue-cli-service build --mode development --dest ./dist/mp/miniprogram/common --watch

/Users/huoxd/Desktop/FUCK/小程序/kbone/binnie/node_modules/neo-async/async.js:16
    throw new Error('Callback was already called.');
    ^

Error: Callback was already called.
    at throwError (/Users/huoxd/Desktop/FUCK/小程序/kbone/binnie/node_modules/neo-async/async.js:16:11)
    at /Users/huoxd/Desktop/FUCK/小程序/kbone/binnie/node_modules/neo-async/async.js:2818:7
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
![截屏2020-02-11上午10 07 18](https://user-images.githubusercontent.com/18095882/74206419-4e525980-4cb6-11ea-8754-1e90727922dd.png)

**Comment by JuneAndGreen** [comment]
没能复现，使用 https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo4 这个demo会有同样问题么？

**Comment by huoxiangdong** [comment]
> 没能复现，使用 https://github.com/wechat-miniprogram/kbone/tree/develop/examples/demo4 这个demo会有同样问题么？

demo4 我跑起来没问题，但是新建项目有问题
```bash
vue create demo
vue add kbone
yarn mp
```
就报错

我nodejs，vue-cli,vue都是最新版，
node v13.8.0
@vue/cli 4.2.2

**Comment by JuneAndGreen** [comment]
@vue/clie 创建的项目依赖升级了，因为一些不兼容的插件导致旧版本的vue-cli-plugin-kbone插件会报错。刚已发布新版本对其进行修复，可以尝试一下vue-cli-plugin-kbone@0.8.0以上版本。
